id: ID959BDFD
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T14:24:43+00:00'
last_modified: '2022-06-07T13:39:03.854078+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS16407
  title: མ་མོ་རོལ་པ་སྤྱི་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    6D56:
      image_group_id: I8LS16418
      title: ''
      total_pages: 366
      order: 1
      base_file: 6D56.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
