id: P000758
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS16407
  title: མ་མོ་རོལ་པ་སྤྱི་བསྡུས།
  author: ''
  volumes:
    55d5925bc04c424ca0921db0402b59b7:
      image_group_id: I8LS16418
      title: ''
      volume_number: 1
      total_pages: 366
      base_file: v001.txt
